//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace GreatLand {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("MbuiSQLDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class MbuiSQLDataSet : global::System.Data.DataSet {
        
        private GetCasinoReportDataTable tableGetCasinoReport;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public MbuiSQLDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected MbuiSQLDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["GetCasinoReport"] != null)) {
                    base.Tables.Add(new GetCasinoReportDataTable(ds.Tables["GetCasinoReport"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public GetCasinoReportDataTable GetCasinoReport {
            get {
                return this.tableGetCasinoReport;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            MbuiSQLDataSet cln = ((MbuiSQLDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["GetCasinoReport"] != null)) {
                    base.Tables.Add(new GetCasinoReportDataTable(ds.Tables["GetCasinoReport"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableGetCasinoReport = ((GetCasinoReportDataTable)(base.Tables["GetCasinoReport"]));
            if ((initTable == true)) {
                if ((this.tableGetCasinoReport != null)) {
                    this.tableGetCasinoReport.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "MbuiSQLDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/MbuiSQLDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableGetCasinoReport = new GetCasinoReportDataTable();
            base.Tables.Add(this.tableGetCasinoReport);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeGetCasinoReport() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            MbuiSQLDataSet ds = new MbuiSQLDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void GetCasinoReportRowChangeEventHandler(object sender, GetCasinoReportRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class GetCasinoReportDataTable : global::System.Data.TypedTableBase<GetCasinoReportRow> {
            
            private global::System.Data.DataColumn columnCasino;
            
            private global::System.Data.DataColumn columnReservation_Route;
            
            private global::System.Data.DataColumn columnReservation_NumberofSeats;
            
            private global::System.Data.DataColumn columnReservation_TravelDate;
            
            private global::System.Data.DataColumn columnReservation_FirstName;
            
            private global::System.Data.DataColumn columnReservation_LastName;
            
            private global::System.Data.DataColumn columnReservation_Email;
            
            private global::System.Data.DataColumn columnReservation_Phone;
            
            private global::System.Data.DataColumn columnReservation_Notes;
            
            private global::System.Data.DataColumn columnReservation_CreateDate;
            
            private global::System.Data.DataColumn columnReservation_LastUpdate;
            
            private global::System.Data.DataColumn columnReservation_PersonUpdate;
            
            private global::System.Data.DataColumn columnReservation_Cancel;
            
            private global::System.Data.DataColumn columnReservation_Confirmation;
            
            private global::System.Data.DataColumn columnReservation_Traveler1Name;
            
            private global::System.Data.DataColumn columnReservation_Traveler2Name;
            
            private global::System.Data.DataColumn columnReservation_Traveler3Name;
            
            private global::System.Data.DataColumn columnReservation_Traveler4Name;
            
            private global::System.Data.DataColumn columnReservation_Traveler5Name;
            
            private global::System.Data.DataColumn columnReservation_Traveler6Name;
            
            private global::System.Data.DataColumn columnReservation_TravelDisclosure;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GetCasinoReportDataTable() {
                this.TableName = "GetCasinoReport";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal GetCasinoReportDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected GetCasinoReportDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CasinoColumn {
                get {
                    return this.columnCasino;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_RouteColumn {
                get {
                    return this.columnReservation_Route;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_NumberofSeatsColumn {
                get {
                    return this.columnReservation_NumberofSeats;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_TravelDateColumn {
                get {
                    return this.columnReservation_TravelDate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_FirstNameColumn {
                get {
                    return this.columnReservation_FirstName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_LastNameColumn {
                get {
                    return this.columnReservation_LastName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_EmailColumn {
                get {
                    return this.columnReservation_Email;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_PhoneColumn {
                get {
                    return this.columnReservation_Phone;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_NotesColumn {
                get {
                    return this.columnReservation_Notes;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_CreateDateColumn {
                get {
                    return this.columnReservation_CreateDate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_LastUpdateColumn {
                get {
                    return this.columnReservation_LastUpdate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_PersonUpdateColumn {
                get {
                    return this.columnReservation_PersonUpdate;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_CancelColumn {
                get {
                    return this.columnReservation_Cancel;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_ConfirmationColumn {
                get {
                    return this.columnReservation_Confirmation;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_Traveler1NameColumn {
                get {
                    return this.columnReservation_Traveler1Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_Traveler2NameColumn {
                get {
                    return this.columnReservation_Traveler2Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_Traveler3NameColumn {
                get {
                    return this.columnReservation_Traveler3Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_Traveler4NameColumn {
                get {
                    return this.columnReservation_Traveler4Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_Traveler5NameColumn {
                get {
                    return this.columnReservation_Traveler5Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_Traveler6NameColumn {
                get {
                    return this.columnReservation_Traveler6Name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Reservation_TravelDisclosureColumn {
                get {
                    return this.columnReservation_TravelDisclosure;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GetCasinoReportRow this[int index] {
                get {
                    return ((GetCasinoReportRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GetCasinoReportRowChangeEventHandler GetCasinoReportRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GetCasinoReportRowChangeEventHandler GetCasinoReportRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GetCasinoReportRowChangeEventHandler GetCasinoReportRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GetCasinoReportRowChangeEventHandler GetCasinoReportRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddGetCasinoReportRow(GetCasinoReportRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GetCasinoReportRow AddGetCasinoReportRow(
                        string Casino, 
                        string Reservation_Route, 
                        int Reservation_NumberofSeats, 
                        System.DateTime Reservation_TravelDate, 
                        string Reservation_FirstName, 
                        string Reservation_LastName, 
                        string Reservation_Email, 
                        string Reservation_Phone, 
                        string Reservation_Notes, 
                        System.DateTime Reservation_CreateDate, 
                        System.DateTime Reservation_LastUpdate, 
                        string Reservation_PersonUpdate, 
                        int Reservation_Cancel, 
                        string Reservation_Confirmation, 
                        string Reservation_Traveler1Name, 
                        string Reservation_Traveler2Name, 
                        string Reservation_Traveler3Name, 
                        string Reservation_Traveler4Name, 
                        string Reservation_Traveler5Name, 
                        string Reservation_Traveler6Name, 
                        string Reservation_TravelDisclosure) {
                GetCasinoReportRow rowGetCasinoReportRow = ((GetCasinoReportRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Casino,
                        Reservation_Route,
                        Reservation_NumberofSeats,
                        Reservation_TravelDate,
                        Reservation_FirstName,
                        Reservation_LastName,
                        Reservation_Email,
                        Reservation_Phone,
                        Reservation_Notes,
                        Reservation_CreateDate,
                        Reservation_LastUpdate,
                        Reservation_PersonUpdate,
                        Reservation_Cancel,
                        Reservation_Confirmation,
                        Reservation_Traveler1Name,
                        Reservation_Traveler2Name,
                        Reservation_Traveler3Name,
                        Reservation_Traveler4Name,
                        Reservation_Traveler5Name,
                        Reservation_Traveler6Name,
                        Reservation_TravelDisclosure};
                rowGetCasinoReportRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowGetCasinoReportRow);
                return rowGetCasinoReportRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                GetCasinoReportDataTable cln = ((GetCasinoReportDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new GetCasinoReportDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnCasino = base.Columns["Casino"];
                this.columnReservation_Route = base.Columns["Reservation_Route"];
                this.columnReservation_NumberofSeats = base.Columns["Reservation_NumberofSeats"];
                this.columnReservation_TravelDate = base.Columns["Reservation_TravelDate"];
                this.columnReservation_FirstName = base.Columns["Reservation_FirstName"];
                this.columnReservation_LastName = base.Columns["Reservation_LastName"];
                this.columnReservation_Email = base.Columns["Reservation_Email"];
                this.columnReservation_Phone = base.Columns["Reservation_Phone"];
                this.columnReservation_Notes = base.Columns["Reservation_Notes"];
                this.columnReservation_CreateDate = base.Columns["Reservation_CreateDate"];
                this.columnReservation_LastUpdate = base.Columns["Reservation_LastUpdate"];
                this.columnReservation_PersonUpdate = base.Columns["Reservation_PersonUpdate"];
                this.columnReservation_Cancel = base.Columns["Reservation_Cancel"];
                this.columnReservation_Confirmation = base.Columns["Reservation_Confirmation"];
                this.columnReservation_Traveler1Name = base.Columns["Reservation_Traveler1Name"];
                this.columnReservation_Traveler2Name = base.Columns["Reservation_Traveler2Name"];
                this.columnReservation_Traveler3Name = base.Columns["Reservation_Traveler3Name"];
                this.columnReservation_Traveler4Name = base.Columns["Reservation_Traveler4Name"];
                this.columnReservation_Traveler5Name = base.Columns["Reservation_Traveler5Name"];
                this.columnReservation_Traveler6Name = base.Columns["Reservation_Traveler6Name"];
                this.columnReservation_TravelDisclosure = base.Columns["Reservation_TravelDisclosure"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnCasino = new global::System.Data.DataColumn("Casino", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCasino);
                this.columnReservation_Route = new global::System.Data.DataColumn("Reservation_Route", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_Route);
                this.columnReservation_NumberofSeats = new global::System.Data.DataColumn("Reservation_NumberofSeats", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_NumberofSeats);
                this.columnReservation_TravelDate = new global::System.Data.DataColumn("Reservation_TravelDate", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_TravelDate);
                this.columnReservation_FirstName = new global::System.Data.DataColumn("Reservation_FirstName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_FirstName);
                this.columnReservation_LastName = new global::System.Data.DataColumn("Reservation_LastName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_LastName);
                this.columnReservation_Email = new global::System.Data.DataColumn("Reservation_Email", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_Email);
                this.columnReservation_Phone = new global::System.Data.DataColumn("Reservation_Phone", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_Phone);
                this.columnReservation_Notes = new global::System.Data.DataColumn("Reservation_Notes", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_Notes);
                this.columnReservation_CreateDate = new global::System.Data.DataColumn("Reservation_CreateDate", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_CreateDate);
                this.columnReservation_LastUpdate = new global::System.Data.DataColumn("Reservation_LastUpdate", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_LastUpdate);
                this.columnReservation_PersonUpdate = new global::System.Data.DataColumn("Reservation_PersonUpdate", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_PersonUpdate);
                this.columnReservation_Cancel = new global::System.Data.DataColumn("Reservation_Cancel", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_Cancel);
                this.columnReservation_Confirmation = new global::System.Data.DataColumn("Reservation_Confirmation", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_Confirmation);
                this.columnReservation_Traveler1Name = new global::System.Data.DataColumn("Reservation_Traveler1Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_Traveler1Name);
                this.columnReservation_Traveler2Name = new global::System.Data.DataColumn("Reservation_Traveler2Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_Traveler2Name);
                this.columnReservation_Traveler3Name = new global::System.Data.DataColumn("Reservation_Traveler3Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_Traveler3Name);
                this.columnReservation_Traveler4Name = new global::System.Data.DataColumn("Reservation_Traveler4Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_Traveler4Name);
                this.columnReservation_Traveler5Name = new global::System.Data.DataColumn("Reservation_Traveler5Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_Traveler5Name);
                this.columnReservation_Traveler6Name = new global::System.Data.DataColumn("Reservation_Traveler6Name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_Traveler6Name);
                this.columnReservation_TravelDisclosure = new global::System.Data.DataColumn("Reservation_TravelDisclosure", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnReservation_TravelDisclosure);
                this.columnCasino.MaxLength = 25;
                this.columnReservation_Route.AllowDBNull = false;
                this.columnReservation_Route.MaxLength = 10;
                this.columnReservation_NumberofSeats.AllowDBNull = false;
                this.columnReservation_TravelDate.AllowDBNull = false;
                this.columnReservation_FirstName.AllowDBNull = false;
                this.columnReservation_FirstName.MaxLength = 50;
                this.columnReservation_LastName.AllowDBNull = false;
                this.columnReservation_LastName.MaxLength = 50;
                this.columnReservation_Email.AllowDBNull = false;
                this.columnReservation_Email.MaxLength = 50;
                this.columnReservation_Phone.AllowDBNull = false;
                this.columnReservation_Phone.MaxLength = 50;
                this.columnReservation_Notes.MaxLength = 2147483647;
                this.columnReservation_CreateDate.AllowDBNull = false;
                this.columnReservation_LastUpdate.AllowDBNull = false;
                this.columnReservation_PersonUpdate.AllowDBNull = false;
                this.columnReservation_PersonUpdate.MaxLength = 50;
                this.columnReservation_Confirmation.AllowDBNull = false;
                this.columnReservation_Confirmation.MaxLength = 20;
                this.columnReservation_Traveler1Name.MaxLength = 20;
                this.columnReservation_Traveler2Name.MaxLength = 20;
                this.columnReservation_Traveler3Name.MaxLength = 20;
                this.columnReservation_Traveler4Name.MaxLength = 20;
                this.columnReservation_Traveler5Name.MaxLength = 20;
                this.columnReservation_Traveler6Name.MaxLength = 20;
                this.columnReservation_TravelDisclosure.MaxLength = 20;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GetCasinoReportRow NewGetCasinoReportRow() {
                return ((GetCasinoReportRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new GetCasinoReportRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(GetCasinoReportRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.GetCasinoReportRowChanged != null)) {
                    this.GetCasinoReportRowChanged(this, new GetCasinoReportRowChangeEvent(((GetCasinoReportRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.GetCasinoReportRowChanging != null)) {
                    this.GetCasinoReportRowChanging(this, new GetCasinoReportRowChangeEvent(((GetCasinoReportRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.GetCasinoReportRowDeleted != null)) {
                    this.GetCasinoReportRowDeleted(this, new GetCasinoReportRowChangeEvent(((GetCasinoReportRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.GetCasinoReportRowDeleting != null)) {
                    this.GetCasinoReportRowDeleting(this, new GetCasinoReportRowChangeEvent(((GetCasinoReportRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveGetCasinoReportRow(GetCasinoReportRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                MbuiSQLDataSet ds = new MbuiSQLDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "GetCasinoReportDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class GetCasinoReportRow : global::System.Data.DataRow {
            
            private GetCasinoReportDataTable tableGetCasinoReport;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal GetCasinoReportRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableGetCasinoReport = ((GetCasinoReportDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Casino {
                get {
                    try {
                        return ((string)(this[this.tableGetCasinoReport.CasinoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Casino\' in table \'GetCasinoReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGetCasinoReport.CasinoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Reservation_Route {
                get {
                    return ((string)(this[this.tableGetCasinoReport.Reservation_RouteColumn]));
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_RouteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Reservation_NumberofSeats {
                get {
                    return ((int)(this[this.tableGetCasinoReport.Reservation_NumberofSeatsColumn]));
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_NumberofSeatsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime Reservation_TravelDate {
                get {
                    return ((global::System.DateTime)(this[this.tableGetCasinoReport.Reservation_TravelDateColumn]));
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_TravelDateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Reservation_FirstName {
                get {
                    return ((string)(this[this.tableGetCasinoReport.Reservation_FirstNameColumn]));
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_FirstNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Reservation_LastName {
                get {
                    return ((string)(this[this.tableGetCasinoReport.Reservation_LastNameColumn]));
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_LastNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Reservation_Email {
                get {
                    return ((string)(this[this.tableGetCasinoReport.Reservation_EmailColumn]));
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_EmailColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Reservation_Phone {
                get {
                    return ((string)(this[this.tableGetCasinoReport.Reservation_PhoneColumn]));
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_PhoneColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Reservation_Notes {
                get {
                    try {
                        return ((string)(this[this.tableGetCasinoReport.Reservation_NotesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Reservation_Notes\' in table \'GetCasinoReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_NotesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime Reservation_CreateDate {
                get {
                    return ((global::System.DateTime)(this[this.tableGetCasinoReport.Reservation_CreateDateColumn]));
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_CreateDateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime Reservation_LastUpdate {
                get {
                    return ((global::System.DateTime)(this[this.tableGetCasinoReport.Reservation_LastUpdateColumn]));
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_LastUpdateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Reservation_PersonUpdate {
                get {
                    return ((string)(this[this.tableGetCasinoReport.Reservation_PersonUpdateColumn]));
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_PersonUpdateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Reservation_Cancel {
                get {
                    try {
                        return ((int)(this[this.tableGetCasinoReport.Reservation_CancelColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Reservation_Cancel\' in table \'GetCasinoReport\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_CancelColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Reservation_Confirmation {
                get {
                    return ((string)(this[this.tableGetCasinoReport.Reservation_ConfirmationColumn]));
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_ConfirmationColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Reservation_Traveler1Name {
                get {
                    try {
                        return ((string)(this[this.tableGetCasinoReport.Reservation_Traveler1NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Reservation_Traveler1Name\' in table \'GetCasinoReport\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_Traveler1NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Reservation_Traveler2Name {
                get {
                    try {
                        return ((string)(this[this.tableGetCasinoReport.Reservation_Traveler2NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Reservation_Traveler2Name\' in table \'GetCasinoReport\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_Traveler2NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Reservation_Traveler3Name {
                get {
                    try {
                        return ((string)(this[this.tableGetCasinoReport.Reservation_Traveler3NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Reservation_Traveler3Name\' in table \'GetCasinoReport\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_Traveler3NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Reservation_Traveler4Name {
                get {
                    try {
                        return ((string)(this[this.tableGetCasinoReport.Reservation_Traveler4NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Reservation_Traveler4Name\' in table \'GetCasinoReport\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_Traveler4NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Reservation_Traveler5Name {
                get {
                    try {
                        return ((string)(this[this.tableGetCasinoReport.Reservation_Traveler5NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Reservation_Traveler5Name\' in table \'GetCasinoReport\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_Traveler5NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Reservation_Traveler6Name {
                get {
                    try {
                        return ((string)(this[this.tableGetCasinoReport.Reservation_Traveler6NameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Reservation_Traveler6Name\' in table \'GetCasinoReport\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_Traveler6NameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Reservation_TravelDisclosure {
                get {
                    try {
                        return ((string)(this[this.tableGetCasinoReport.Reservation_TravelDisclosureColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Reservation_TravelDisclosure\' in table \'GetCasinoReport\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tableGetCasinoReport.Reservation_TravelDisclosureColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCasinoNull() {
                return this.IsNull(this.tableGetCasinoReport.CasinoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCasinoNull() {
                this[this.tableGetCasinoReport.CasinoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsReservation_NotesNull() {
                return this.IsNull(this.tableGetCasinoReport.Reservation_NotesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetReservation_NotesNull() {
                this[this.tableGetCasinoReport.Reservation_NotesColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsReservation_CancelNull() {
                return this.IsNull(this.tableGetCasinoReport.Reservation_CancelColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetReservation_CancelNull() {
                this[this.tableGetCasinoReport.Reservation_CancelColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsReservation_Traveler1NameNull() {
                return this.IsNull(this.tableGetCasinoReport.Reservation_Traveler1NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetReservation_Traveler1NameNull() {
                this[this.tableGetCasinoReport.Reservation_Traveler1NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsReservation_Traveler2NameNull() {
                return this.IsNull(this.tableGetCasinoReport.Reservation_Traveler2NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetReservation_Traveler2NameNull() {
                this[this.tableGetCasinoReport.Reservation_Traveler2NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsReservation_Traveler3NameNull() {
                return this.IsNull(this.tableGetCasinoReport.Reservation_Traveler3NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetReservation_Traveler3NameNull() {
                this[this.tableGetCasinoReport.Reservation_Traveler3NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsReservation_Traveler4NameNull() {
                return this.IsNull(this.tableGetCasinoReport.Reservation_Traveler4NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetReservation_Traveler4NameNull() {
                this[this.tableGetCasinoReport.Reservation_Traveler4NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsReservation_Traveler5NameNull() {
                return this.IsNull(this.tableGetCasinoReport.Reservation_Traveler5NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetReservation_Traveler5NameNull() {
                this[this.tableGetCasinoReport.Reservation_Traveler5NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsReservation_Traveler6NameNull() {
                return this.IsNull(this.tableGetCasinoReport.Reservation_Traveler6NameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetReservation_Traveler6NameNull() {
                this[this.tableGetCasinoReport.Reservation_Traveler6NameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsReservation_TravelDisclosureNull() {
                return this.IsNull(this.tableGetCasinoReport.Reservation_TravelDisclosureColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetReservation_TravelDisclosureNull() {
                this[this.tableGetCasinoReport.Reservation_TravelDisclosureColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class GetCasinoReportRowChangeEvent : global::System.EventArgs {
            
            private GetCasinoReportRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GetCasinoReportRowChangeEvent(GetCasinoReportRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GetCasinoReportRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591